# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Jekyll configuration
sass:
    sass_dir: _sass
    style: compressed

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.    
permalink:           pretty
relative_permalinks: true
excerpt_separator:   '<!--snippet-->'
# Setup
title:               'CS 4501: Information Retrieval'
tagline:             'Fall 2015 &middot; <a href="http://www.cs.virginia.edu/">CS@UVa</a>'
description:         'Introduction to Information Retrieval'
host:								 'http://www.cs.virginia.edu/'
baseurl:         '/~hw5x/Course/IR2015/_site'
url:             '/~hw5x/Course/IR2015/_site'
logo:								 'UVA_Rotunda_Logo.png'
# About/contact
author:
  name:              Hongning Wang
  url:               'http://www.cs.virginia.edu/~hw5x/'
  email:             hw5x@virginia.edu

# Custom vars
version:             1.0.0


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
